In [43]:

import tensorflow as tf
keras = tf.keras
from keras import Model

import pandas as pd
import numpy as np

# Make numpy values easier to read.
np.set_printoptions(precision=4, suppress=True)

In [44]:
filename = "C:\MakeAIWork\simulations\car\control_client\data_files\sonar_kevin.csv"

In [45]:
sonar_01_train = pd.read_csv(filename, sep = ',')

In [46]:
sonar_01_train.head()

1.4512   1.271  1.7665  -22
0  1.4520  1.2716  1.7669  -22
1  1.4506  1.2705  1.7660  -22
2  1.4486  1.2688  1.7645  -22
3  1.4458  1.2666  1.7625  -22
4  1.4420  1.2635  1.7597  -22

In [47]:
# sonar_01_sensors = sonar_01_train.copy()
# sonar_01_labels = sonar_01_sensors.pop('Steering Angle')

In [48]:
# sonar_01_sensors.head()

In [49]:
# sonar_01_labels.head()

De input (sensoren/afstanden) en output kunnen ook op een andere manier gescheiden 
opgehaald worden uit het DataFrame:

In [50]:
sonar_01_labels = sonar_01_train.iloc[:, [3]]
sonar_01_sensors = sonar_01_train.iloc[:,[0, 1, 2]] # met .loc kan je labels gebruiken 'Sensor 1' etc.

In [51]:
# sonar_01_labels.head()

In [52]:
sonar_01_sensors.head()

1.4512   1.271  1.7665
0  1.4520  1.2716  1.7669
1  1.4506  1.2705  1.7660
2  1.4486  1.2688  1.7645
3  1.4458  1.2666  1.7625
4  1.4420  1.2635  1.7597

In [53]:
sonar_01_sensors = np.array(sonar_01_sensors)

In [54]:
print(sonar_01_sensors)

[[1.452  1.2716 1.7669]
 [1.4506 1.2705 1.766 ]
 [1.4486 1.2688 1.7645]
 ...
 [1.9834 1.74   1.3532]
 [1.9834 1.74   1.3532]
 [1.9834 1.74   1.3532]]


In [55]:
# tf.random.set_seed(1) Not working correctly/at all?

Wanneer er een Normalizer gebruikt wordt, moet dit ook voor de auto gebruikt worden. 

Wellicht niet per se nodig, al geeft het wel een beter resultaat op de loss

In [56]:
# normalize = keras.layers.Normalization()
# normalize.adapt(sonar_01_sensors)

# Anders: 'normalize,' toevoegen aan de lagen van onderstaand model

In [57]:
norm_sonar_01_model = tf.keras.Sequential([
  keras.Input(shape = (3,)),
  keras.layers.Dense(8, activation = 'relu'), 
  keras.layers.Dense(8, activation = 'relu'),
  keras.layers.Dense(1)
])  

In [58]:
norm_sonar_01_model.compile(loss = tf.keras.losses.MeanSquaredError(), metrics = ['accuracy'], 
                            optimizer = tf.keras.optimizers.Adam(learning_rate=0.01))

Er kan ook nog een 'clipnorm = 1' aan de optimizer toegevoegd worden

In [59]:
# norm_sonar_01_model.summary()

In [60]:
norm_sonar_01_model.fit(sonar_01_sensors, sonar_01_labels, epochs=100) # Check

Epoch 1/100
157/157 [==============================] - 1s 4ms/step - loss: 62.0537 - accuracy: 0.2239
Epoch 2/100
157/157 [==============================] - 1s 3ms/step - loss: 33.9725 - accuracy: 0.3827
Epoch 3/100
157/157 [==============================] - 0s 3ms/step - loss: 19.8804 - accuracy: 0.4539
Epoch 4/100
157/157 [==============================] - 0s 3ms/step - loss: 14.1322 - accuracy: 0.4980
Epoch 5/100
157/157 [==============================] - 1s 3ms/step - loss: 11.2201 - accuracy: 0.5457
Epoch 6/100
157/157 [==============================] - 1s 3ms/step - loss: 10.9956 - accuracy: 0.5198
Epoch 7/100
157/157 [==============================] - 1s 3ms/step - loss: 12.6459 - accuracy: 0.5020
Epoch 8/100
157/157 [==============================] - 1s 3ms/step - loss: 8.7106 - accuracy: 0.5937
Epoch 9/100
157/157 [==============================] - 1s 3ms/step - loss: 8.3303 - accuracy: 0.5651
Epoch 10/100
157/157 [==============================] - 1s 3ms/step - loss: 7.2673 -

In [61]:
norm_sonar_01_model.save('norm_sonar_01_model')

INFO:tensorflow:Assets written to: norm_sonar_01_model\assets


In [62]:
# tf.keras.Sequential.save("C:\MakeAIWork\simulations\car\control_client", norm_sonar_01_model)

We can load the model which was saved using the load_model() method present in the tensorflow module.

Syntax: tensorflow.keras.models.load_model(location/model_name)

The location along with the model name is passed as a parameter in this method.

NOTE: If we specify “.h5”, the model will be saved in hdf5 format; if no extension is specified, the model will be saved in TensorFlow native format.

In [63]:
# norm_sonar_01_model.evaluate()

- Training en Test (& Validatie?) aanmaken?
- Hoe data opslaan en exporteren? Check
- Accuracy? - Done
- Model prediction! model.predict inputs + real values (array?)

https://www.tensorflow.org/guide/keras/save_and_serialize