In [1]:

import tensorflow as tf
keras = tf.keras
from keras import Model

import pandas as pd
import numpy as np

# Make numpy values easier to read.
np.set_printoptions(precision=4, suppress=True)

from sklearn.model_selection import train_test_split

In [2]:
filename = "../sonar_kevin.csv"

In [3]:
sonar_01_train = pd.read_csv(filename, sep = ',')

In [4]:
sonar_01_train.head()

1.4512   1.271  1.7665  -22
0  1.4520  1.2716  1.7669  -22
1  1.4506  1.2705  1.7660  -22
2  1.4486  1.2688  1.7645  -22
3  1.4458  1.2666  1.7625  -22
4  1.4420  1.2635  1.7597  -22

In [5]:
# sonar_01_sensors = sonar_01_train.copy()
# sonar_01_labels = sonar_01_sensors.pop('Steering Angle')

In [6]:
# sonar_01_sensors.head()

In [7]:
# sonar_01_labels.head()

De input (sensoren/afstanden) en output kunnen ook op een andere manier gescheiden 
opgehaald worden uit het DataFrame:

In [8]:
sonar_01_labels = sonar_01_train.iloc[:, [3]]
sonar_01_sensors = sonar_01_train.iloc[:,[0, 1, 2]] # met .loc kan je labels gebruiken 'Sensor 1' etc.

In [9]:
# sonar_01_labels.head()

In [10]:
# sonar_01_sensors.head()

In [11]:
sonar_01_sensors = np.array(sonar_01_sensors)
sonar_01_labels = np.array(sonar_01_labels)

In [12]:
# print(sonar_01_sensors)

In [13]:
# val_sonar_01_sensors = np.array(sonar_01_sensors [500:799])
# val_sonar_01_labels = np.array(sonar_01_labels [500:799])

In [14]:
sonar_01_sensors_train, sonar_01_sensors_test, sonar_01_labels_train, sonar_01_labels_test = train_test_split(sonar_01_sensors, sonar_01_labels, test_size = 0.20)

In [15]:
normalize = keras.layers.Normalization()
normalize.adapt(sonar_01_sensors_train) 
normalize.adapt(sonar_01_sensors_test)
normalize.adapt(sonar_01_labels_train) 
normalize.adapt(sonar_01_labels_test)

In [16]:
print(sonar_01_sensors_train) 
print()
print(sonar_01_sensors_test)
print()
print(sonar_01_labels_train)
print() 
print(sonar_01_labels_test)

[[1.5933 1.3879 1.1602]
 [0.9166 0.5431 3.094 ]
 [1.9766 1.8443 0.8298]
 ...
 [1.9411 1.6598 1.106 ]
 [2.7866 1.3585 1.3375]
 [2.1213 1.3212 1.3573]]

[[1.6714 1.2722 1.1805]
 [1.7732 1.7211 1.319 ]
 [1.5002 1.4175 1.2736]
 ...
 [1.3213 1.4077 1.0856]
 [1.8603 1.4969 1.1418]
 [1.8523 1.5404 1.2837]]

[[  0]
 [-22]
 [  0]
 ...
 [  0]
 [  0]
 [  0]]

[[  0]
 [  0]
 [  0]
 [  0]
 [ 22]
 [  0]
 [-22]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [ 22]
 [  0]
 [  0]
 [ 22]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [ 22]
 [ 22]
 [  0]
 [  0]
 [ 22]
 [ 22]
 [  0]
 [ 22]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [ 22]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [ 22]
 [ 22]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [ 22]
 [  0]
 [ 22]
 [  0]
 [  0]
 [ 22]
 [ 22]
 [  0]
 [ 22]
 [ 22]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [-22]
 [  0]
 [  0]
 [ 22]
 [  0]
 [  0]
 [  0]
 [  0]
 [ 22]
 [-22]
 [  0]
 [  0

In [17]:
norm_sonar_01_model = tf.keras.Sequential([
  normalize,
  keras.Input(shape = (3,)),
  keras.layers.Dense(16, activation = 'relu'), 
  keras.layers.Dense(16, activation = 'relu'),
  keras.layers.Dense(1)
])  

In [18]:
norm_sonar_01_model.compile(loss = tf.keras.losses.MeanSquaredError(), metrics = ['accuracy', 'mae'], 
                            optimizer = tf.keras.optimizers.Adam(learning_rate=0.01))

In [19]:
norm_sonar_01_model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 normalization (Normalizatio  (None, 3)                7         
 n)                                                              
                                                                 
 input_1 (InputLayer)        multiple                  0         
                                                                 
 dense (Dense)               (None, 16)                64        
                                                                 
 dense_1 (Dense)             (None, 16)                272       
                                                                 
 dense_2 (Dense)             (None, 1)                 17        
                                                                 
Total params: 360
Trainable params: 353
Non-trainable params: 7
__________________________________________________________

In [20]:
norm_sonar_01_model.fit(sonar_01_sensors_train, sonar_01_labels_train, epochs=100)

Epoch 1/100
125/125 [==============================] - 7s 5ms/step - loss: 92.0349 - accuracy: 0.0896 - mae: 6.3233
Epoch 2/100
125/125 [==============================] - 1s 5ms/step - loss: 62.4488 - accuracy: 0.1867 - mae: 5.7746
Epoch 3/100
125/125 [==============================] - 1s 5ms/step - loss: 46.3881 - accuracy: 0.3091 - mae: 5.1179
Epoch 4/100
125/125 [==============================] - 1s 5ms/step - loss: 39.6235 - accuracy: 0.3307 - mae: 4.6673
Epoch 5/100
125/125 [==============================] - 1s 5ms/step - loss: 36.7944 - accuracy: 0.3577 - mae: 4.3390
Epoch 6/100
125/125 [==============================] - 1s 5ms/step - loss: 33.6568 - accuracy: 0.3977 - mae: 3.9952
Epoch 7/100
125/125 [==============================] - 1s 5ms/step - loss: 30.5220 - accuracy: 0.4095 - mae: 3.7230
Epoch 8/100
125/125 [==============================] - 1s 5ms/step - loss: 27.9223 - accuracy: 0.4313 - mae: 3.4719
Epoch 9/100
125/125 [==============================] - 1s 5ms/step - los

In [21]:
norm_sonar_01_model.evaluate(sonar_01_sensors_test, sonar_01_labels_test)

32/32 [==============================] - 1s 9ms/step - loss: 5.8487 - accuracy: 0.6006 - mae: 1.0236


[5.848673343658447, 0.6006006002426147, 1.023626685142517]

In [22]:
norm_sonar_01_model.predict(sonar_01_sensors_test)

32/32 [==============================] - 0s 4ms/step


array([[  0.5216],
       [  0.3826],
       [  0.1799],
       [  0.4103],
       [ 22.2051],
       [  0.4612],
       [-13.5913],
       [  1.0873],
       [  0.4282],
       [  0.5611],
       [ -6.2491],
       [  0.3339],
       [ -2.8811],
       [ -4.1633],
       [  0.4216],
       [  0.5116],
       [  0.2941],
       [ 22.1633],
       [  4.1974],
       [ -2.7358],
       [ 22.0137],
       [  0.5506],
       [  0.112 ],
       [  0.3718],
       [  0.5636],
       [  0.2554],
       [ 22.2376],
       [ 22.0079],
       [  0.4995],
       [ 16.0192],
       [ 22.1909],
       [ 22.2027],
       [  0.1547],
       [ 21.9981],
       [  0.3194],
       [  0.5052],
       [  0.3275],
       [  0.1238],
       [  0.4528],
       [  0.3389],
       [ -0.5899],
       [ -1.3218],
       [  0.2598],
       [ 22.2377],
       [  3.2913],
       [  0.4542],
       [  0.43  ],
       [  1.3246],
       [  0.526 ],
       [ 21.5511],
       [ 22.4971],
       [  0.3512],
       [  0.

In [23]:
norm_sonar_01_model.save('C:/MakeAIWork/simulations/car/control_client/tensorflow/modelT')

INFO:tensorflow:Assets written to: C:/MakeAIWork/simulations/car/control_client/tensorflow/modelT\assets


- Training en Test aanmaken?
- Validatie. Done!
- Hoe data opslaan en exporteren? Check
- Accuracy? - Done
- Model prediction! model.predict inputs + real values (array?) Done!

https://www.tensorflow.org/guide/keras/save_and_serialize

tf.random.set_seed(1) Not working correctly/at all?

https://www.askpython.com/python-modules/saving-loading-models-tensorflow